"""
Django settings for MightyDigits project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBLIC_DIR = os.path.join(BASE_DIR, 'public')
MEDIA_URL = '/public/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'public')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1&3z!=v(!gp0#_8w&ctk=5wuqu7yo#$yb)!bh+j=8x!)#al&x@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'accounts',
    'sampleAppOAuth2',
    'mightyapp',
    'adminApp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MightyDigits.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MightyDigits.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mighty',
        'USER': 'root',
        'PASSWORD': '',
        'HOST' : 'localhost',
        'PORT' : '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# OAuth specific variables
# DISCOVERY_DOCUMENT = 'https://developer.api.intuit.com/.well-known/openid_sandbox_configuration/'
# CLIENT_ID = 'AB1sJdgwWXB5s3L2Fe3k1zl8ENpudtkrQWEk7B3WbwCG1lFrSW'
# CLIENT_SECRET = 'Znnnb0tolQBQW5woHWLz7p4YPLaGKDPMLBFFuDyF'
# REDIRECT_URI = 'http://localhost:8000/sampleAppOAuth2/authCodeHandler'
# ACCOUNTING_SCOPE = 'com.intuit.quickbooks.accounting'
# OPENID_SCOPES = ['openid', 'profile', 'email', 'phone', 'address']
# GET_APP_SCOPES = ['com.intuit.quickbooks.accounting', 'openid', 'profile', 'email', 'phone', 'address']
# SANDBOX_QBO_BASEURL = 'https://sandbox-quickbooks.api.intuit.com'
# SANDBOX_PROFILE_URL = 'https://sandbox-accounts.platform.intuit.com/v1/openid_connect/userinfo'
# ID_TOKEN_ISSUER = 'https://oauth.platform.intuit.com/op/v1'
# Production
DISCOVERY_DOCUMENT = 'https://developer.api.intuit.com/.well-known/openid_configuration/'
CLIENT_ID = 'AB17KsPganRnw6Jxd0UFIdz6Rtq8oVBZtbEmhZ21UbqEGgDS8o'
CLIENT_SECRET = 'JAy5tysUrCFNoIxELOk2KbFJ6AteMFH9GcpFV2I2'
# CLIENT_ID = 'ABZJntvUEzfcKDxJBUaB09k0C2ybRM2tFRHXmaePBkRT1WyXff'
# CLIENT_SECRET = '0PIWcVvulYU7gi4CQFMVInSL1GQTjehjpwjsSKgk'
REDIRECT_URI = 'https://app.mightydigits.com/sampleAppOAuth2/authCodeHandler'
REDIRECT_URI2 = 'https://app.mightydigits.com/sampleAppOAuth2/authCodeHandler2'
ACCOUNTING_SCOPE = 'com.intuit.quickbooks.accounting'
OPENID_SCOPES = ['openid', 'profile', 'email', 'phone', 'address']
GET_APP_SCOPES = ['com.intuit.quickbooks.accounting', 'openid', 'profile', 'email', 'phone', 'address']
SANDBOX_QBO_BASEURL = 'https://quickbooks.api.intuit.com'
SANDBOX_PROFILE_URL = 'https://accounts.platform.intuit.com/v1/openid_connect/userinfo'
ID_TOKEN_ISSUER = 'https://oauth.platform.intuit.com/op/v1'


# Other Settings
DEFAULT_PASSWORD = '123123'

# Email settings
SENDGRID_API_KEY = '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'

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey' # this is exactly the value 'apikey'
EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'youremail@gmail.com'
# EMAIL_HOST_PASSWORD = 'email_password'
# EMAIL_PORT = 587

# Toggle sandbox mode (when running in DEBUG mode)
# SENDGRID_SANDBOX_MODE_IN_DEBUG=True

# echo to stdout or any other file-like object that is passed to the backend via the stream kwarg.
SENDGRID_ECHO_TO_STDOUT=True